### ISSUE TITLE
Using AD B2C global admin accounts to call Graph API

### ISSUE THREAD

**Issue by gopal-amlekar** [Azure-Samples/ms-identity-b2c-javascript-nodejs-management#2]
### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Clone the sample.
> Create and Configure AD B2C app registration to accept accounts from this organization and social accounts, external AD accounts (The 3rd option)
> The AD B2C tenant I have has some accounts created via self-sign-up earlier. One of the accounts there (created with gmail identity provider) is assigned with a Global Administrator permissions for the AD B2C instance.
> Configure sample with client ID and Tenant ID (as described in README)
```
const msalConfig = {
    auth: {
        clientId: "1e4952b6-XXXXXXXXXXXXXXXXXX", // This is the ONLY mandatory field that you need to supply.
        authority: "https://login.microsoftonline.com/9f7c26a4-XXXXXXXXXXXXXXXXXX",
        redirectUri: "http://localhost:3000", // You must register this URI on Azure Portal/App Registration.
      },
    cache: {
        cacheLocation: "localStorage", // This configures where your cache will be stored
        storeAuthStateInCookie: false, // Set this to "true" if you are having issues on IE11 or Edge
    },
};
```

> Run the sample.
> It does not show me the sign-in / sign-up policy I have in my AD B2C tenant. Also the code in this sample does not have any reference to the sign-in / sign-up policy. It only shows the Microsoft account sign-in and then takes me to my organization sign-in process. 

### Any log messages given by the failure
>

### Expected/desired behavior
> I would expect to have the users from my AD B2C be able to call Graph APIs provided they have got permissions in the tenant. Is it possible to achieve this?
> If not possible, does it mean that I should always have a dedicated app running for managing users via Graph APIs? 

### OS and Version?
> Windows 10, Chrome

### Versions
> MSAL 2.8.0 as per the code

### Mention any other details that might be useful
> I have setup my AD B2C tenant based on this sample - [https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa)

Here is the screenshot of my sign-in/sign-up page based on this sample.
![image](https://user-images.githubusercontent.com/3242003/105449929-545f0180-5c9f-11eb-8f55-21cf1e99c16e.png)

So, if I run your sample, I can only get the Microsoft account sign-in option.

![image](https://user-images.githubusercontent.com/3242003/105449960-680a6800-5c9f-11eb-8009-de400941335b.png)

Thank you very much for all your efforts. It is very helpful.

Just for additional details, here is what I want to achieve:
Develop a SPA which can sign-in/sign-up users from any AD tenant or external Identity providers. 
Therefore use AD B2C for registering this SPA.
Then configure one of the users as global admin for the AD B2C.
Have the SPA call Graph APIs to further manage users (CRUD operations with users).

Is this a feasible option with AD B2C and MSAL? If not, any suggestions how to do this?

Thanks again!

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by derisen** [comment]
@gopal-amlekar you're welcome : ) So the application you sign-in/sign-up users (call it consumer-app) will be separate from the application that is used for managing users/calling graph API (call it management-app). 

They can use the same app registration that you created on Azure portal. However, the consumer-app will be configured to have authority string set to your sing-in/sign-up policy (e.g. `YOUR_TENANT_NAME.b2clogin.com/YOUR_TENANT_NAME.onmicrosoft.com/b2c_1_susi`), the management-app authority string on the other hand will be set to AAD endpoint (e.g. `https://login.microsoftonline.com/YOUR_TENANT_ID_OR_NAME/`)

So if I understand correctly you want to sign-up a consumer account with gmail identity provider, assign it administrator role, and use it with management-app? In that case, yes, the consumer account won't be able to sign-in to management-app. But what you can do is to [assign a local identity](https://docs.microsoft.com/graph/api/user-post-users?view=graph-rest-1.0&tabs=http#example-2-create-a-user-with-social-and-local-account-identities) to that consumer account, and have her sign-in with that identity to the management-app.

Does that help? (sorry the PR is not merged yet but will be soon)

**Comment by gopal-amlekar** [comment]
@derisen  thank you very much for your reply. Yes, it does help.

I did try using the long.microsoftonlline.com/tenantID as the authority and it did work with the AD users, for example the users I created from within the b2c portal with a mytenant@onmicrosot.com domain. It didn't work with the users who signed up from my consumer app as you have described exactly.

So if I understand it correctly, for user management via Graph API, only the users in the AD b2c tenant can do that. With a self-signed up user with an email or social account, they can't access Graph API. Is that correct?

Thank you again!

**Comment by derisen** [comment]
@gopal-amlekar that's pretty much the case, eventually the user account that will get admin privileges will need to be represented the B2C tenant.

But it might still possible to allow that user to login with her gmail address by using invitation. Take a look at [this](https://docs.microsoft.com/azure/active-directory-b2c/user-overview#guest-user) and [this](https://docs.microsoft.com/azure/active-directory/external-identities/user-properties) document. I haven't tried this myself so I'm not sure it would work. You can find [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md#b2c-and-invite-flow) more about how the invitation flow happens.

Let me know if that helps.

**Comment by gopal-amlekar** [comment]
@derisen I think this makes it clearer to me now. I tried inviting users to my B2C instance from the portal. It then asked the user to create a Microsoft account using their email ID. This meant a new credentials but they can use the email ID to login. It matches with this state:

> 
_State 2: Homed in a Microsoft or other account and represented as a guest user in the host organization. In this case, the guest user signs in with a Microsoft account or a social account (google.com or similar). The invited user's identity is created as a Microsoft account in the inviting organization’s directory during offer redemption._

Overall, I realize that I am trying to do a little more complicated scenario. I am trying to make it work with a b2b kind of scenario but while retaining the b2c experience. So I need to do things little differently now. I will think over a bit again how I can make it work.

Meanwhile, if there is any contribution to your code that I can do, I will be happy to, thank you very much for your support!

**Comment by derisen** [comment]
@gopal-amlekar no worries : ) Best of luck with your scenario! If you can achieve what you want and would like to share your experience with others, I can help you document it and display it in the repo (either as a new sample, or as a wiki item)

Other than that, you are always welcome to make a PR if you catch an issue/bug in the repo.

**Comment by gopal-amlekar** [comment]
Thank you @derisen. Yes I will come back with how I go about it. For now, I will close this issue and yes if there is anything I spot, I will create a PR as much as I can. Thank you again, this thread has been really super useful for me.
