### ISSUE TITLE
Self-Service Scenario possible?

### ISSUE THREAD

**Issue by f0o** [Azure-Samples/ms-identity-b2c-javascript-nodejs-management#4]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

Hi,

I'm trying to understand if a self service portal using AD B2C is possible.

The Users should be allowed to pull and edit their own profile data but so far any token that a client gets issued from the AD B2C login page is unable to query graph.microsoft.com/v1.0/me...

It's worth to note that all Users are logging in through Socials as that's the main reason why AD B2C was chosen to begin with.

Is this behavior even supported? I'm not finding any clear statement whether AD B2C Client Tokens are support or not.

Many threads many years old say they're not but a lot can change since 2017 ;)

**Comment by derisen** [comment]
@f0o unfortunately, B2C apps cannot obtain MS Graph access tokens for users via delegated permissions, so no change on that part. Please refer to [this document](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/working-with-b2c.md) for more on working with B2C.

Of course, users can edit their B2C profiles (not their Graph profile) via a user-flow, as is illustrated in [this sample](https://github.com/Azure-Samples/ms-identity-b2c-javascript-spa).

**Comment by f0o** [comment]
Hi @derisen Thanks for the clarification, it gets confusing with so much information scattered around.
